-- Smazani predesleho schematu
BEGIN
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_prehled_letadel';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_letadlo_model_id';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE vyskolen'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE provadi'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE certifikat'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE test'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE mezinarodni_test'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE osobni_letadlo'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE nakladni_letadlo';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE letadlo'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE technik'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE model_letadla'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/


CREATE TABLE model_letadla (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vyrobce VARCHAR2(255),
    nazev_modelu VARCHAR2(255),
    cislo_modelu INT
);

CREATE TABLE technik (
    rodne_cislo VARCHAR2(11) PRIMARY KEY,
    jmeno VARCHAR2(255),
    prijmeni VARCHAR2(255),
    specializace VARCHAR2(255),
    -- Integritni omezeni pro rodne cislo (můze zacinat 0 napr.)
    CONSTRAINT chk_rodne_cislo CHECK (REGEXP_LIKE(rodne_cislo, '^[0-9]{9,10}$'))
);


/* * VYSVeTLENi REALIZACE VZTAHU GENERALIZACE/SPECIALIZACE:
 * Pro modelovani vztahu mezi entitou 'Letadlo' a jejimi specializacemi 'Osobni letadlo' 
 * a 'Nakladni letadlo' byla zvolena metoda "Tabulka pro kazdou tridu".
 * * Princip reseni:
 * 1. Nadrazena tabulka (letadlo) obsahuje spolecne atributy pro vsechny typy letadel.
 * 2. Podrizene tabulky (osobni_letadlo, nakladni_letadlo) obsahuji pouze specificke atributy.
 * 3. Vazba 1:1 je realizovana tak, ze primarni klic specializovane tabulky (vyrobni_cislo) 
 * je zaroveň cizim klicem (Foreign Key) odkazujicim na primarni klic tabulky rodicovske.
 * * Vyhodou tohoto pristupu je vysoka mira normalizace a absence nadbytecnych NULL hodnot 
 * u specifickych atributů.
 */

CREATE TABLE letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    model_id INT NOT NULL,
    aktivni NUMBER(1) DEFAULT 1,
    dolet INT,
    datum_vyroby DATE,
    
    CONSTRAINT chk_dolet CHECK (dolet > 0),
    CONSTRAINT fk_letadlo_model FOREIGN KEY (model_id) REFERENCES model_letadla(id)
);

CREATE TABLE nakladni_letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    nosnost INT,
    chlazeni VARCHAR2(255),
    velikost_prostoru VARCHAR2(255),
    CONSTRAINT fk_nakladni_letadlo FOREIGN KEY (vyrobni_cislo) REFERENCES letadlo(vyrobni_cislo)
);

CREATE TABLE osobni_letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    pocet_sedadel INT,
    pocet_toalet INT,
    pocet_trid INT,
    CONSTRAINT fk_osobni_letadlo FOREIGN KEY (vyrobni_cislo) REFERENCES letadlo(vyrobni_cislo)
);

CREATE TABLE mezinarodni_test (
    id INT PRIMARY KEY,
    nazev VARCHAR2(255),
    min_limit VARCHAR2(255),
    max_limit VARCHAR2(255)
);

CREATE TABLE test (
    id INT PRIMARY KEY,
    mezinarodni_test_id INT,
    vyrobni_cislo_letadla INT NOT NULL,
    stav VARCHAR2(20),
    rodne_cislo VARCHAR2(11),
    -- Test můze byt buďto splnen nebo nesplnen. Vychozi stav je nesplnen
    CONSTRAINT chk_stav_hodnoty CHECK (stav IN ('splneno', 'nesplneno')),
    CONSTRAINT fk_test_letadlo FOREIGN KEY (vyrobni_cislo_letadla) REFERENCES letadlo(vyrobni_cislo),
    CONSTRAINT fk_test_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo),
    CONSTRAINT fk_test_mezinarodni FOREIGN KEY (mezinarodni_test_id) REFERENCES mezinarodni_test(id)
);

CREATE TABLE certifikat (
    test_id INT PRIMARY KEY,
    nazev_certifikatu VARCHAR2(255),
    datum_vystaveni DATE,
    archivovano NUMBER(1),
    CONSTRAINT fk_certifikat_test FOREIGN KEY (test_id) REFERENCES test(id)
);

CREATE TABLE provadi (
    id_testu INT,
    rodne_cislo VARCHAR2(11),
    datum_provedeni DATE NOT NULL,
    popis_provedeni VARCHAR2(255),
    PRIMARY KEY (id_testu, rodne_cislo, datum_provedeni),
    CONSTRAINT fk_provadi_test FOREIGN KEY (id_testu) REFERENCES test(id),
    CONSTRAINT fk_provadi_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo)
);

CREATE TABLE vyskolen (
    model_id INT,
    rodne_cislo VARCHAR2(11),
    datum_skoleni DATE NOT NULL,
    platnost_skoleni DATE NOT NULL,
    PRIMARY KEY (model_id, rodne_cislo),
    CONSTRAINT fk_vyskolen_model FOREIGN KEY (model_id) REFERENCES model_letadla(id),
    CONSTRAINT fk_vyskolen_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo)
);

INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('Boeing', 'Max', 767);
INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('Airbus', 'Ultra', 67);
INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('General Dynamics', 'Falcon', 47);

INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('0123456789', 'Adam', 'Sandler', 'motory');
INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('0622458783', 'Petr', 'Fiala', 'ovladaci plochy');
INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('5222458783', 'Anakin', 'Skywalker', 'vsechno');

INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (1, 2, 1, 1600, TO_DATE('1998-02-28', 'YYYY-MM-DD'));
INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (2, 2, 1, 2300, TO_DATE('1977-05-25', 'YYYY-MM-DD'));
INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (3, 1, 0, 5, TO_DATE('2001-09-11', 'YYYY-MM-DD'));

INSERT INTO nakladni_letadlo (vyrobni_cislo, nosnost, chlazeni, velikost_prostoru) VALUES (1, 500, 'vodni', '1000');
INSERT INTO osobni_letadlo (vyrobni_cislo, pocet_sedadel, pocet_toalet, pocet_trid) VALUES (2, 130, 4, 3);
INSERT INTO osobni_letadlo (vyrobni_cislo, pocet_sedadel, pocet_toalet, pocet_trid) VALUES (3, 50, 2, 2);

INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (1, 'Test odolnosti podvozku', 'poskrabani kol', 'neni stanoven');
INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (2, 'Test průdkeho narazu do budovy', 'preziti pilota', 'preziti vsech');
INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (3, 'Test brzdne vzdalenosti', '1km', '5km');

INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (1, 3, 1, 'nesplneno', '0123456789');
INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (2, 1, 2, 'splneno', '0622458783');
INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (3, 2, 3, 'nesplneno', '5222458783');

INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (1, 'Funkcni brzdovy system', TO_DATE('2026-03-20', 'YYYY-MM-DD'), 1);
INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (2, 'Proverena odolnost', TO_DATE('2008-09-25', 'YYYY-MM-DD'), 1);
INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (3, 'Integrita trupu', TO_DATE('2010-12-08', 'YYYY-MM-DD'), 0);

INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (1, '0123456789', TO_DATE('2026-03-10', 'YYYY-MM-DD'), 'Brzdy OK');
INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (2, '0622458783', TO_DATE('2026-03-12', 'YYYY-MM-DD'), 'Podvozek OK');
INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (3, '5222458783', TO_DATE('2026-03-15', 'YYYY-MM-DD'), 'Simulace narazu');

INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (1, '0123456789', TO_DATE('2020-05-20', 'YYYY-MM-DD'), TO_DATE('2030-05-20', 'YYYY-MM-DD'));
INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (2, '0622458783', TO_DATE('2021-10-10', 'YYYY-MM-DD'), TO_DATE('2026-10-10', 'YYYY-MM-DD'));
INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (3, '5222458783', TO_DATE('2015-01-01', 'YYYY-MM-DD'), TO_DATE('2099-12-31', 'YYYY-MM-DD'));

COMMIT;


-- Dotaz pro vypsani vsech letadel, vypisuje jejich hodnoty sloupců --
SELECT l.vyrobni_cislo, m.vyrobce, m.nazev_modelu, l.datum_vyroby
FROM letadlo l
JOIN model_letadla m ON l.model_id = m.id;

-- Vypsani vsech modelů letadel, ktere jsou evidovany v databazi
SELECT 
    m.nazev_modelu, 
    m.cislo_modelu, 
    l.vyrobni_cislo, 
    l.dolet
FROM model_letadla m
JOIN letadlo l ON m.id = l.model_id;

-- Vypisuje technikovy údaje, vcetne certifikatů kazdeho technika --
SELECT t.jmeno, t.prijmeni, c.nazev_certifikatu
FROM technik t
JOIN test test_tab ON t.rodne_cislo = test_tab.rodne_cislo
JOIN certifikat c ON test_tab.id = c.test_id;

-- Vypsani poctu vsech letadel na konkretniho vyrobce --
SELECT m.vyrobce, COUNT(l.vyrobni_cislo) AS pocet_letadel
FROM model_letadla m
LEFT JOIN letadlo l ON m.id = l.model_id
GROUP BY m.vyrobce;

-- Vypsani průmeru doletu vsech modelů letadel --
SELECT m.nazev_modelu, AVG(l.dolet) AS prumerny_dolet
FROM letadlo l
JOIN model_letadla m ON l.model_id = m.id
GROUP BY m.nazev_modelu;

-- Vybere vsechny testy, ktere maji prirazen platny zaznam v tabulce mezinarodnich testů --
SELECT * FROM test t
WHERE EXISTS (
    SELECT 1 
    FROM mezinarodni_test mt 
    WHERE mt.id = t.mezinarodni_test_id
);

-- Vypis vyrobnich cisel letadel, ktery splnili testy
SELECT vyrobni_cislo, dolet, datum_vyroby
FROM letadlo
WHERE vyrobni_cislo IN (
    SELECT vyrobni_cislo_letadla 
    FROM test 
    WHERE stav = 'splneno'
);

-- Trigger 1 - je technik skolen na dane letadlo pred provedenim testu? --
CREATE OR REPLACE TRIGGER check_technik_skoleni
BEFORE INSERT ON provadi
FOR EACH ROW
DECLARE
    v_model_id letadlo.model_id%TYPE;
    v_count NUMBER;
BEGIN
    -- Model letadla, ktere se testuje --
    SELECT model_id INTO v_model_id
    FROM letadlo L JOIN test T ON L.vyrobni_cislo = T.vyrobni_cislo_letadla
    WHERE T.id = :NEW.id_testu;

    -- Kontrola platnosti skoleni technika --
    SELECT COUNT(*) INTO v_count
    FROM vyskolen
    WHERE rodne_cislo = :NEW.rodne_cislo
        AND model_id = v_model_id
        AND platnost_skoleni >= :NEW.datum_provedeni;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Technik neni vyskolen pro toto letadlo');
    END IF;
END;
/

-- Triger 2 - Jestli letadlo nema splneny test, stane se prozatim nepouzitelny
CREATE OR REPLACE TRIGGER letadlo_zpusobile
AFTER UPDATE OF stav ON test
FOR EACH ROW
WHEN (NEW.stav = 'nesplneno')
BEGIN
    UPDATE letadlo
    SET aktivni = 0
    WHERE vyrobni_cislo = :NEW.vyrobni_cislo_letadla;
    DBMS_OUTPUT.PUT_LINE('Letadlo ' || :NEW.vyrobni_cislo_letadla || ' nema spleneno pozadavky pro jeho aktivni uzivani.');
END;
/

-- Uroven letadla podle doletu a pridava pocet ziskanych certifikatu
WITH pocet_certifikatu AS (
    SELECT vyrobni_cislo_letadla, COUNT(C.test_id) as cert_count
    FROM test T
    LEFT JOIN certifikat C ON T.id = C.test_id
    GROUP BY vyrobni_cislo_letadla
)
SELECT 
    L.vyrobni_cislo,
    M.nazev_modelu,
    -- Razeni podle doletu --
    CASE 
        WHEN L.dolet > 2000 THEN 'Dalkove letadlo'
        WHEN L.dolet BETWEEN 1000 AND 2000 THEN 'Stredni trat'
        ELSE 'Regionalni letadlo'
    END AS kategorie_doletu,
    -- Pouziti NVL specifiky pro Oracle (null value handling) --
    NVL(PC.cert_count, 0) as celkem_certifikatu
FROM letadlo L
JOIN model_letadla M ON L.model_id = M.id
LEFT JOIN pocet_certifikatu PC ON L.vyrobni_cislo = PC.vyrobni_cislo_letadla;

GRANT ALL ON letadlo TO XVORACM00;
GRANT ALL ON model_letadla TO XVORACM00;
GRANT ALL ON test TO XVORACM00;
GRANT ALL ON technik TO XVORACM00;
GRANT ALL ON provadi TO XVORACM00;
GRANT ALL ON certifikat TO XVORACM00;
GRANT ALL ON mezinarodni_test TO XVORACM00;
GRANT ALL ON vyskolen TO XVORACM00;
GRANT ALL ON nakladni_letadlo TO XVORACM00;
GRANT ALL ON osobni_letadlo TO XVORACM00;

-- Procedura 1. Projde vsechny testy letadla a vypise jejich vysledky --
CREATE OR REPLACE PROCEDURE vypis_testy_letadla (
    p_vyrobni_cislo IN letadlo.vyrobni_cislo%TYPE
)
AS
    CURSOR c_testy IS
        SELECT id, stav
        FROM test
        WHERE vyrobni_cislo_letadla = p_vyrobni_cislo;

    v_test c_testy%ROWTYPE;
BEGIN
    OPEN c_testy;
    LOOP
        FETCH c_testy INTO v_test;
        EXIT WHEN c_testy%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Test ID: ' || v_test.id || ', stav: ' || v_test.stav
        );
    END LOOP;
    CLOSE c_testy;
END;
/

BEGIN
    vypis_testy_letadla(1);
END;
/

-- Procedura 2. Vyhleda certifikat podle testu a nastavi ho jako archivovany. --
CREATE OR REPLACE PROCEDURE archivuj_certifikat (
    p_test_id IN certifikat.test_id%TYPE
)
AS
    v_certifikat certifikat%ROWTYPE;
BEGIN
    SELECT *
    INTO v_certifikat
    FROM certifikat
    WHERE test_id = p_test_id;

    UPDATE certifikat
    SET archivovano = 1
    WHERE test_id = p_test_id;

    DBMS_OUTPUT.PUT_LINE('Certifikat archivovan: ' || v_certifikat.nazev_certifikatu);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Certifikat pro dany test neexistuje.');
END;
/

BEGIN
    archivuj_certifikat(1);
END;
/

-- EXPLAIN PLAN bez indexu, Spocita pocet letadel daneho vyrobce. --
EXPLAIN PLAN FOR
SELECT m.vyrobce, COUNT(l.vyrobni_cislo) AS pocet_letadel
FROM model_letadla m
JOIN letadlo l ON m.id = l.model_id
GROUP BY m.vyrobce;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


-- EXPLAIN PLAN s indexem, Index umoznuje rychlejsi vyhledavani --
CREATE INDEX idx_letadlo_model_id ON letadlo(model_id);

EXPLAIN PLAN FOR
SELECT m.vyrobce, COUNT(l.vyrobni_cislo) AS pocet_letadel
FROM model_letadla m
JOIN letadlo l ON m.id = l.model_id
GROUP BY m.vyrobce;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


-- MATERIALIZED VIEW. Vypssani dat z tabulek letadlo a model_letadla --
CREATE MATERIALIZED VIEW mv_prehled_letadel
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT l.vyrobni_cislo, m.vyrobce, m.nazev_modelu, l.dolet
FROM XVORACM00.letadlo l
JOIN XVORACM00.model_letadla m
    ON l.model_id = m.id;

SELECT * FROM mv_prehled_letadel;

EXEC DBMS_MVIEW.REFRESH('MV_PREHLED_LETADEL');

SELECT * FROM mv_prehled_letadel;

-- Testy pro triggery


-- Aby byly videt hlasky z DBMS_OUTPUT
SET SERVEROUTPUT ON

PROMPT 1. Kontrola skoleni technika

BEGIN
    -- Technik Anakin se pokusi testovat letadlo Airbus, na ktery nema skoleni
    INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni)
    VALUES (1, '5222458783', TO_DATE('2026-04-01', 'YYYY-MM-DD'), 'Nepovoleny pokus');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CHYBA ZACHYCENA: ' || SQLERRM);
END;
/

PROMPT 2. Deaktivace letadlo pri nesplneni pozadavku

-- Je letadlo ok pred testem?
SELECT vyrobni_cislo, aktivni FROM letadlo WHERE vyrobni_cislo = 2;

-- Zmena na stavu na nesplneno -> vyvola trigger
UPDATE test SET stav = 'nesplneno' WHERE id = 2;

-- Zasahnul trigger spravne?
SELECT vyrobni_cislo, aktivni FROM letadlo WHERE vyrobni_cislo = 2;
