-- Smazani predesleho schematu
BEGIN EXECUTE IMMEDIATE 'DROP TABLE vyskolen'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE provadi'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE certifikat'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE test'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE mezinarodni_test'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE osobni_letadlo'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE nakladni_letadlo'; EXCEPTION WHEN OTHERS THEN NULL; END; /

BEGIN EXECUTE IMMEDIATE 'DROP TABLE letadlo'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE technik'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE model_letadla'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/

CREATE TABLE model_letadla (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vyrobce VARCHAR2(255),
    nazev_modelu VARCHAR2(255),
    cislo_modelu INT
);

CREATE TABLE technik (
    rodne_cislo VARCHAR2(11) PRIMARY KEY,
    jmeno VARCHAR2(255),
    prijmeni VARCHAR2(255),
    specializace VARCHAR2(255),
    -- Integritni omezeni pro rodne cislo (můze zacinat 0 napr.)
    CONSTRAINT chk_rodne_cislo CHECK (REGEXP_LIKE(rodne_cislo, '^[0-9]{9,10}$'))
);


/* * VYSVeTLENi REALIZACE VZTAHU GENERALIZACE/SPECIALIZACE:
 * Pro modelovani vztahu mezi entitou 'Letadlo' a jejimi specializacemi 'Osobni letadlo' 
 * a 'Nakladni letadlo' byla zvolena metoda "Tabulka pro kazdou tridu".
 * * Princip reseni:
 * 1. Nadrazena tabulka (letadlo) obsahuje spolecne atributy pro vsechny typy letadel.
 * 2. Podrizene tabulky (osobni_letadlo, nakladni_letadlo) obsahuji pouze specificke atributy.
 * 3. Vazba 1:1 je realizovana tak, ze primarni klic specializovane tabulky (vyrobni_cislo) 
 * je zaroveň cizim klicem (Foreign Key) odkazujicim na primarni klic tabulky rodicovske.
 * * Vyhodou tohoto pristupu je vysoka mira normalizace a absence nadbytecnych NULL hodnot 
 * u specifickych atributů.
 */

CREATE TABLE letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    model_id INT NOT NULL,
    aktivni NUMBER(1) DEFAULT 1,
    dolet INT,
    datum_vyroby DATE,
    
    CONSTRAINT chk_dolet CHECK (dolet > 0),
    CONSTRAINT fk_letadlo_model FOREIGN KEY (model_id) REFERENCES model_letadla(id)
);

CREATE TABLE nakladni_letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    nosnost INT,
    chlazeni VARCHAR2(255),
    velikost_prostoru VARCHAR2(255),
    CONSTRAINT fk_nakladni_letadlo FOREIGN KEY (vyrobni_cislo) REFERENCES letadlo(vyrobni_cislo)
);

CREATE TABLE osobni_letadlo (
    vyrobni_cislo INT PRIMARY KEY,
    pocet_sedadel INT,
    pocet_toalet INT,
    pocet_trid INT,
    CONSTRAINT fk_osobni_letadlo FOREIGN KEY (vyrobni_cislo) REFERENCES letadlo(vyrobni_cislo)
);

CREATE TABLE mezinarodni_test (
    id INT PRIMARY KEY,
    nazev VARCHAR2(255),
    min_limit VARCHAR2(255),
    max_limit VARCHAR2(255)
);

CREATE TABLE test (
    id INT PRIMARY KEY,
    mezinarodni_test_id INT,
    vyrobni_cislo_letadla INT NOT NULL,
    stav VARCHAR2(20),
    rodne_cislo VARCHAR2(11),
    -- Test můze byt buďto splnen nebo nesplnen. Vychozi stav je nesplnen
    CONSTRAINT chk_stav_hodnoty CHECK (stav IN ('splneno', 'nesplneno')),
    CONSTRAINT fk_test_letadlo FOREIGN KEY (vyrobni_cislo_letadla) REFERENCES letadlo(vyrobni_cislo),
    CONSTRAINT fk_test_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo),
    CONSTRAINT fk_test_mezinarodni FOREIGN KEY (mezinarodni_test_id) REFERENCES mezinarodni_test(id)
);

CREATE TABLE certifikat (
    test_id INT PRIMARY KEY,
    nazev_certifikatu VARCHAR2(255),
    datum_vystaveni DATE,
    archivovano NUMBER(1),
    CONSTRAINT fk_certifikat_test FOREIGN KEY (test_id) REFERENCES test(id)
);

CREATE TABLE provadi (
    id_testu INT,
    rodne_cislo VARCHAR2(11),
    datum_provedeni DATE NOT NULL,
    popis_provedeni VARCHAR2(255),
    PRIMARY KEY (id_testu, rodne_cislo, datum_provedeni),
    CONSTRAINT fk_provadi_test FOREIGN KEY (id_testu) REFERENCES test(id),
    CONSTRAINT fk_provadi_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo)
);

CREATE TABLE vyskolen (
    model_id INT,
    rodne_cislo VARCHAR2(11),
    datum_skoleni DATE NOT NULL,
    platnost_skoleni DATE NOT NULL,
    PRIMARY KEY (model_id, rodne_cislo),
    CONSTRAINT fk_vyskolen_model FOREIGN KEY (model_id) REFERENCES model_letadla(id),
    CONSTRAINT fk_vyskolen_technik FOREIGN KEY (rodne_cislo) REFERENCES technik(rodne_cislo)
);

INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('Boeing', 'Max', 767);
INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('Airbus', 'Ultra', 67);
INSERT INTO model_letadla (vyrobce, nazev_modelu, cislo_modelu) VALUES ('General Dynamics', 'Falcon', 47);

INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('0123456789', 'Adam', 'Sandler', 'motory');
INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('0622458783', 'Petr', 'Fiala', 'ovladaci plochy');
INSERT INTO technik (rodne_cislo, jmeno, prijmeni, specializace) VALUES ('5222458783', 'Anakin', 'Skywalker', 'vsechno');

INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (1, 2, 1, 1600, TO_DATE('1998-02-28', 'YYYY-MM-DD'));
INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (2, 2, 1, 2300, TO_DATE('1977-05-25', 'YYYY-MM-DD'));
INSERT INTO letadlo (vyrobni_cislo, model_id, aktivni, dolet, datum_vyroby) VALUES (3, 1, 0, 5, TO_DATE('2001-09-11', 'YYYY-MM-DD'));

INSERT INTO nakladni_letadlo (vyrobni_cislo, nosnost, chlazeni, velikost_prostoru) VALUES (1, 500, 'vodni', '1000');
INSERT INTO osobni_letadlo (vyrobni_cislo, pocet_sedadel, pocet_toalet, pocet_trid) VALUES (2, 130, 4, 3);
INSERT INTO osobni_letadlo (vyrobni_cislo, pocet_sedadel, pocet_toalet, pocet_trid) VALUES (3, 50, 2, 2);

INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (1, 'Test odolnosti podvozku', 'poskrabani kol', 'neni stanoven');
INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (2, 'Test průdkeho narazu do budovy', 'preziti pilota', 'preziti vsech');
INSERT INTO mezinarodni_test (id, nazev, min_limit, max_limit) VALUES (3, 'Test brzdne vzdalenosti', '1km', '5km');

INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (1, 3, 1, 'nesplneno', '0123456789');
INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (2, 1, 2, 'splneno', '0622458783');
INSERT INTO test (id, mezinarodni_test_id, vyrobni_cislo_letadla, stav, rodne_cislo) VALUES (3, 2, 3, 'nesplneno', '5222458783');

INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (1, 'Funkcni brzdovy system', TO_DATE('2026-03-20', 'YYYY-MM-DD'), 1);
INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (2, 'Proverena odolnost', TO_DATE('2008-09-25', 'YYYY-MM-DD'), 1);
INSERT INTO certifikat (test_id, nazev_certifikatu, datum_vystaveni, archivovano) VALUES (3, 'Integrita trupu', TO_DATE('2010-12-08', 'YYYY-MM-DD'), 0);

INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (1, '0123456789', TO_DATE('2026-03-10', 'YYYY-MM-DD'), 'Brzdy OK');
INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (2, '0622458783', TO_DATE('2026-03-12', 'YYYY-MM-DD'), 'Podvozek OK');
INSERT INTO provadi (id_testu, rodne_cislo, datum_provedeni, popis_provedeni) VALUES (3, '5222458783', TO_DATE('2026-03-15', 'YYYY-MM-DD'), 'Simulace narazu');

INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (1, '0123456789', TO_DATE('2020-05-20', 'YYYY-MM-DD'), TO_DATE('2030-05-20', 'YYYY-MM-DD'));
INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (2, '0622458783', TO_DATE('2021-10-10', 'YYYY-MM-DD'), TO_DATE('2026-10-10', 'YYYY-MM-DD'));
INSERT INTO vyskolen (model_id, rodne_cislo, datum_skoleni, platnost_skoleni) VALUES (3, '5222458783', TO_DATE('2015-01-01', 'YYYY-MM-DD'), TO_DATE('2099-12-31', 'YYYY-MM-DD'));

COMMIT;


-- Dotaz pro vypsani vsech letadel, vypisuje jejich hodnoty sloupců --
SELECT l.vyrobni_cislo, m.vyrobce, m.nazev_modelu, l.datum_vyroby
FROM letadlo l
JOIN model_letadla m ON l.model_id = m.id;

-- Vypsani vsech modelů letadel, ktere jsou evidovany v databazi
SELECT 
    m.nazev_modelu, 
    m.cislo_modelu, 
    l.vyrobni_cislo, 
    l.dolet
FROM model_letadla m
JOIN letadlo l ON m.id = l.model_id;

-- Vypisuje technikovy údaje, vcetne certifikatů kazdeho technika --
SELECT t.jmeno, t.prijmeni, c.nazev_certifikatu
FROM technik t
JOIN test test_tab ON t.rodne_cislo = test_tab.rodne_cislo
JOIN certifikat c ON test_tab.id = c.test_id;

-- Vypsani poctu vsech letadel na konkretniho vyrobce --
SELECT m.vyrobce, COUNT(l.vyrobni_cislo) AS pocet_letadel
FROM model_letadla m
LEFT JOIN letadlo l ON m.id = l.model_id
GROUP BY m.vyrobce;

-- Vypsani průmeru doletu vsech modelů letadel --
SELECT m.nazev_modelu, AVG(l.dolet) AS prumerny_dolet
FROM letadlo l
JOIN model_letadla m ON l.model_id = m.id
GROUP BY m.nazev_modelu;

-- Vybere vsechny testy, ktere maji prirazen platny zaznam v tabulce mezinarodnich testů --
SELECT * FROM test t
WHERE EXISTS (
    SELECT 1 
    FROM mezinarodni_test mt 
    WHERE mt.id = t.mezinarodni_test_id
);

-- Vypis vyrobnich cisel letadel, ktery splnili testy
SELECT vyrobni_cislo, dolet, datum_vyroby
FROM letadlo
WHERE vyrobni_cislo IN (
    SELECT vyrobni_cislo_letadla 
    FROM test 
    WHERE stav = 'splněno'
);